#
# $Id$
#
# Makefile for building subdirectories
#
# $Log$
# Revision 1.2  1994/09/21 22:18:29  jba
# New definitions in CONFIG* files
#
#

EPICS = ../..
include $(EPICS)/config/CONFIG_EXTENSIONS

include $(EPICS)/config/RULES_DIRS

